# Generated by Django 6.0.8 on 2026-09-17 16:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car_Status_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='carfueltype_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fueltype', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='cargeartype_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geartype', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='dummytable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dummyfield', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Car_Detail_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100)),
                ('colour', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('carlocation', models.CharField(max_length=50, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('fueltype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BuyCars.carfueltype_model')),
                ('geartype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BuyCars.cargeartype_model')),
            ],
        ),
        migrations.CreateModel(
            name='Car_Buy_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phonenumber', models.CharField(max_length=11)),
                ('emailid', models.EmailField(max_length=254)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BuyCars.car_detail_model')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('car', 'buyer'), name='carid_and_userid')],
            },
        ),
    ]
