# Generated by Django 6.0.8 on 2026-09-03 16:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BuyCars', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='car_buy_model',
            constraint=models.UniqueConstraint(fields=('car', 'buyer'), name='carid_and_userid'),
        ),
    ]
