# Generated by Django 6.0.8 on 2026-09-17 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BuyCars', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='dummytable',
        ),
        migrations.AddField(
            model_name='car_detail_model',
            name='post_status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='BuyCars.car_status_model'),
            preserve_default=False,
        ),
    ]
