# Generated by Django 6.0.8 on 2026-09-18 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BuyCars', '0002_delete_dummytable_car_detail_model_post_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car_detail_model',
            name='post_status',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='BuyCars.car_status_model'),
        ),
    ]
