# Generated by Django 6.0.8 on 2026-09-21 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BuyCars', '0003_alter_car_detail_model_post_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='car_detail_model',
            name='brand',
            field=models.CharField(default='no brand', max_length=50),
            preserve_default=False,
        ),
    ]
